### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and '_GenericAlias'

### ISSUE THREAD

**Issue by uhuhh** [davila7/file-gpt#3]
Error when open the link.

Python 3.9.14
Redhat EL 9.1

  You can now view your Streamlit app in your browser.

  Network URL: http://x.x.x.x:8501
  External URL: http://x.x.x.x:8501

2023-02-22 22:18:53.256 `st.experimental_memo` is deprecated. Please use the new command `st.cache_data` instead, which has the same behavior. More information [in our docs](https://docs.streamlit.io/library/advanced-features/caching).
2023-02-22 22:18:53.260 `st.experimental_memo` is deprecated. Please use the new command `st.cache_data` instead, which has the same behavior. More information [in our docs](https://docs.streamlit.io/library/advanced-features/caching).
2023-02-22 22:18:53.261 `st.experimental_memo` is deprecated. Please use the new command `st.cache_data` instead, which has the same behavior. More information [in our docs](https://docs.streamlit.io/library/advanced-features/caching).
2023-02-22 22:18:53.262 `st.experimental_memo` is deprecated. Please use the new command `st.cache_data` instead, which has the same behavior. More information [in our docs](https://docs.streamlit.io/library/advanced-features/caching).
2023-02-22 22:18:53.263 Uncaught app exception
Traceback (most recent call last):
  File "/home/chatgpt/.local/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "/home/chatgpt/file-gpt/app.py", line 4, in <module>
    from utils import (
  File "/home/chatgpt/file-gpt/utils.py", line 162, in <module>

    def wrap_text_in_html(text: str | List[str]) -> str:
TypeError: unsupported operand type(s) for |: 'type' and '_GenericAlias'

![Captura2](https://user-images.githubusercontent.com/37223957/220821091-23057e11-184c-48d1-9d28-deef409be08b.JPG)
![Captura](https://user-images.githubusercontent.com/37223957/220821092-b462b8a7-0f99-49ef-930b-63f8fe5d179a.JPG)

**Comment by alealima** [comment]
The issue will be resolved if you upgrade to python 3.10+
